# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Tue Feb 23 20:45:59 2021
#

import wx


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LogPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LogPanel.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        vs_log = wx.BoxSizer(wx.VERTICAL)

        hs_log = wx.BoxSizer(wx.HORIZONTAL)
        vs_log.Add(hs_log, 1, wx.EXPAND, 0)

        self.tc_log = wx.TextCtrl(self, wx.ID_ANY, "",
                                  style=wx.TE_MULTILINE | wx.TE_READONLY | wx.TE_RIGHT | wx.TE_WORDWRAP)
        hs_log.Add(self.tc_log, 1, wx.EXPAND, 0)

        self.SetSizer(vs_log)

        self.Layout()

        self.Bind(wx.EVT_TEXT_MAXLEN, self.on_log_max_len, self.tc_log)
        # end wxGlade

    def on_log_max_len(self, event):  # wxGlade: LogPanel.<event_handler>
        print("Event handler 'on_log_max_len' not implemented!")
        event.Skip()

# end of class LogPanel
