#!/usr/bin/env python3
#  -*- coding: utf-8 -*-
__author__ = "Ivo Woltring"
__revised__ = "$revised: 2021-03-10 09:36:54$"
__copyright__ = "Copyright (c) 2021 Ivo Woltring"
__license__ = "Apache 2.0"
__doc__ = """
Customized ArtProvider that will incorporate my own images by its own prefix.
The images are coming from the ivonet.image.images.py file
that file is generated by the img2py application.
"""

import wx

import ivonet

try:
    from ivonet.image.images import catalog, index
except ImportError:
    raise ImportError("The images file was not found. Did you forget to do generate them?")


class IvoNetArtProvider(wx.ArtProvider):
    """Customized ArtProvider that will incorporate my own images by its own prefix.
    """

    def __init__(self, art_id_prefix=ivonet.ART_PREFIX):
        self.prefix = art_id_prefix
        self.catalog = catalog
        self.index = index

        wx.ArtProvider.__init__(self)

    def generate_art_id_list(self):
        return [self.prefix + name.upper() for name in self.index]

    def CreateBitmap(self, art_id, client, size):
        if art_id.startswith(self.prefix):
            name = art_id[len(self.prefix):].lower()
            if name in self.catalog:
                return self.catalog[name].GetBitmap()

        return wx.NullBitmap


if __name__ == '__main__':
    print(IvoNetArtProvider().generate_art_id_list())
